# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c62e3ea9e68f3cf8aba982763b96fe8"
name = "checkout-ui-ext"
handle = "checkout-ui-ext-42"
application_url = "https://seem-introduces-rows-attraction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2e5b25fd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://seem-introduces-rows-attraction.trycloudflare.com/auth/callback",
  "https://seem-introduces-rows-attraction.trycloudflare.com/auth/shopify/callback",
  "https://seem-introduces-rows-attraction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
